name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          echo "[default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation create-stack --stack-name workshop5ennaem \
            --template-body file://template.yaml \
            --region us-east-1 \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Wait for Stack to Complete
        run: |
          aws cloudformation wait stack-create-complete --stack-name workshop5ennaem \
            --region us-east-1 # Replace with your desired AWS region

      - name: Display Stack Outputs
        run: |
          aws cloudformation describe-stacks --stack-name workshop5ennaem \
            --query 'Stacks[0].Outputs' \
            --output table \
            --region us-east-1 # Replace with your desired AWS region
        env:
          AWS_PAGER: ""
